[package]
name = "photobooth-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v4l = "0.12.1"
nokhwa = "0.9.4"
eframe = "0.17.0"
image = "0.24.1"